### ISSUE TITLE
make viz for open signal phone

### ISSUE THREAD

**Issue by kra** [breedx2/futel-usage-viz#6]
events are
initial menu accessed from open signal phone
hold the phone menu accessed from open signal phone
hold the phone menu accessed from any other futel phone
hold the phone incoming menu accessed

events are 2019-07-01 through 2020-11-30

this should be a priority and hopefully completed in december 2020
this will allow us to present an engagement report to open signal and racc
this will be important for future fundraising and may help us convince open signal to keep the phone active

**Comment by kra** [comment]
open signal pickups
name hold_the_phone_main
extension 660

open signal hold the phone content
name peoples_homes
name conversations
name missed_connections
extension 660

other futel phone hold the phone content
name peoples_homes
name conversations
name missed_connections
extension not 660

incoming hold the phone menu
name hold_the_phone_incoming
extension any (should only have the incoming extension)


names may change over the course of the implementation, maybe graph these and then check? Check by grepping the metrics with various unmunging/denormalization, check fully by looking at source history?

**Comment by kra** [comment]
I think this issue is resolved when the various existing issues are resolved, plus the data

**Comment by breedx2** [comment]
The above breakdown is SUPER HELPFUL.  Thanks!
Making progress on this, have noticed these two interesting event names:
* hold_the_phone_main_conversations (1 of them)
* hold_the_phone_main_missedconnections (10 of them)

@kra should we ignore or map these to one of the above?

**Comment by breedx2** [comment]
Another small clarification - above it says "other futel phone hold the phone content" and extension not 660...and since the data doesn't have an extension field, one is divinated from the `channel` field.   It looks like there are a few general forms of channel data:

* `SIP/nnn-xxxxxxxx` - looks like futel extensions? true?
* `SIP/ipv4-xxxxxxxx` - <shrug> there are only a couple
* `SIP/twillio-origination-n-xxxxxxxx` 
* `SIP/twillio-termination-xxxxxxxx`
* `SIP/voipms-xxxxxxxx`

I am guessing those last 3 are inbound?  @kra For the purposes of "other futel phone" content, do you wanna also exclude the last 3 formats, or do you just want everything non-opensignal-handset?

**Comment by kra** [comment]
give me access and I will commit an example without bothering to branch

**Comment by kra** [comment]
last 3 are inbound but it might not be reliable and we can probably avoid all that with UI

**Comment by kra** [comment]
early metrics had the name of "peoples-homes" instead of "peoples_homes"
run file through this to normalize everything to peoples_homes

cat metrics* | sed 's/peoples-homes/peoples_homes/'

**Comment by breedx2** [comment]
Yup, what you're describing is encompassed by #2 .  :metal:

**Comment by breedx2** [comment]
The viz is there.  Maybe we could close this and open other new issues for specific tweaks.
